### ISSUE TITLE
Copy of former `TODO` file

### ISSUE THREAD

**Issue by haraldh** [dracutdevs/dracut#1068]
Copied from the former `TODO`. Split out to individual issues as appropriate.

## GENERATOR TODO

* [ ] report errors on missing files in check()
* [ ] remove wait for swap devs, if no "resume=" is given on the kernel command line
* [ ] remove wait for swap devs, if the "resume" dracut module is not included (omitted)
* [ ] add presets (predefined set of modules)
* [ ] add interpreter/plugin-scripts to be sourced at the beginning or end (can use dracut-functions)
* [ ] add mechanism for module specific command line options
* [ ] pkg-config integration, to make it easy for other packages to use us.
* [ ] default module specification could use some work
* [ ] udev rule copying, as mentioned above, is a bit too hard-coded

## CODE TODO

* [ ] document more functions
* [ ] make function vars local, and prefix with "_"

# Future Enhancement Requests

* [ ] run ssh server to enter crypto password or perform debugging (supported by debian)
* [ ] https://bugzilla.redhat.com/show_bug.cgi?id=524727 - dracut + encrypted root + networking
* [ ] lsinitrd --print-cmdline
* [ ] dracut --print-cmdline error if additional arguments
* [ ] library for cmdline
