### ISSUE TITLE
Testsuite improvements tracker

### ISSUE THREAD

**Issue by mrc0mmand** [dracutdevs/dracut#733]
Tracker for possible testsuite improvements:

 - [ ] use `set -e` for all client/server setup scripts to avoid the VM pretending being 'all set up' yet in the log you notice `/sbin/init: line 114: dhcpd: command not found`
 - [x] test BOTH `network-legacy` and `network-manager` modules
    - right now both Travis & CentOS CI use the legacy module, since NetworkManager is not installed
    - see #732 
 - [ ] test IPv6 along with IPv4 in network-related tests (20-NFS, 30-ISCSI, etc.)
 - [ ] bump the CentOS CI image from F25 to something more recent (and possibly test RHEL8 as well?)
 - [ ] consider testing on different architectures in Travis (aarch64, ppc64le, s390x, see https://docs.travis-ci.com/user/multi-cpu-architectures)
 - TBD

/cc @lnykryn

**Comment by johannbg** [comment]
@mrc0mmand presumably you are no longer working on this? Basically just wondering if we cant close this issue?

**Comment by mrc0mmand** [comment]
> @mrc0mmand presumably you are no longer working on this? Basically just wondering if we cant close this issue?

Unfortunately not, so we can definitely close this.
